### ISSUE TITLE
XOR cipher leaks portion of key

### ISSUE THREAD

**Issue by TheDukeZip** [pdogg/jt65stego#10]
Need to look at this, probably has something to do with the way I am padding the input to make its length a multiple of 8 bytes

**Comment by pdogg** [comment]
Won't XOR always leak when there are repeating chars?

**Comment by TheDukeZip** [comment]
I want to remind myself to double check and look at this later, I don't
think it's supposed to be as bad as it looks

**Comment by TheDukeZip** [comment]
Resolved by padding with random chars. The status byte of each transmission will tell the decoding how many bytes to actually reconstruct during decoding, and which ones were random padding to throw away.

**Comment by TheDukeZip** [comment]
I should add that I'm not saying XOR ciphers are secure or don't leak keys, but now this one is no less secure than any other...

**Comment by pdogg** [comment]
> I should add that I'm not saying XOR ciphers are secure or don't leak
> keys, but now this one is no less secure than any other...

I like that quote! :)

I do like having XOR in there tho...

**Comment by TheDukeZip** [comment]
Actually the more I think about this... The padding chars should be plaintext if you're ciphering plaintext, and random bytes for binary data....
