### ISSUE TITLE
Probably should remove legit calls from test cases

### ISSUE THREAD

**Issue by pdogg** [pdogg/jt65stego#17]
G3LTF etc... don't know who these fine people are but I'm not sure they should be in our final release. I don't want MY call in our final release :)

**Comment by pdogg** [comment]
Also use DD44 for grid location... No secret I live in FN42 but I don't think there's any land in DD44 :)

**Comment by pdogg** [comment]
KA1AAA is legit too :( http://www.qrz.com/db/KA1AAA

**Comment by pdogg** [comment]
kb2bbc ka1aab DD44 

seems like a benign test message

**Comment by TheDukeZip** [comment]
Removed all legit calls from test cases - closing
